version: "3.8"
services:
  backend1:
      container_name: "backend1"
      build:
          context: ./backend1
      ports:
          - "8081:8081"
  backend2:
      container_name: "backend2"
      build:
          context: ./backend2
      ports:
          - "8082:8082"
  proxy:
      container_name: "proxy"
      build:
          context: ./proxy
      ports:
          - "80:80"
          - "443:443"
      volumes:
        - ./certificates:/certificates