name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.4' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install lint tools
        run: make install-tools
      - name: Run gofmt
        run: make gofmt
      - name: Run vet
        run: make vet
      - name: Run errcheck
        run: make errcheck
      - name: Run gosec
        run: make gosec
      - name: Run govulncheck
        run: make govulncheck