name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'stable' ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6.0.0
        with:
          fetch-depth: 0
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install lint tools
        run: make install-tools
      - name: Run lint
        run: make lint